import { Geist, Geist_Mono } from "next/font/google";
import LayoutWrapper from "./layoutwrapper";
import Script from "next/script";
import "../../public/css/style.css";
import "../../public/css/bootstrap.min.css";
import "../../public/lib/animate/animate.min.css";
import "../../public/lib/owlcarousel/assets/owl.carousel.min.css";

// ✅ Fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// ✅ Metadata
export const metadata = {
  title: "Modern Art Builders",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

// ✅ Root Layout
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* ✅ External CSS (use <link>, not <Link>) */}
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
          crossOrigin="anonymous"
        />

        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
          integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13fjL8uCF8a7x6Rkg=="
          referrerPolicy="no-referrer"
        />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin=""
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Jost:wght@500;600;700&family=Open+Sans:wght@400;500&display=swap"
          rel="stylesheet"
        />

        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css"
          rel="stylesheet"
        />

        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css"
          rel="stylesheet"
        />
        <link href="/lib/animate/animate.min.css" rel="stylesheet" />
        <link
          href="/lib/owlcarousel/assets/owl.carousel.min.css"
          rel="stylesheet"
        />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
        />
        <link href="/css/bootstrap.min.css" rel="stylesheet" />
        <link href="/css/style.css" rel="stylesheet" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* ✅ Page Layout */}
        <LayoutWrapper>
          {children}
        </LayoutWrapper>
        {/* ✅ JS Dependencies (optimized loading) */}
        <Script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js" />
        <Script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
          crossOrigin="anonymous"
          strategy="beforeInteractive"
        />
        <Script src="/lib/wow/wow.min.js" strategy="afterInteractive" />
        <Script src="/lib/easing/easing.min.js" strategy="afterInteractive" />
        <Script
          src="/lib/waypoints/waypoints.min.js"
          strategy="afterInteractive"
        />
        <Script
          src="/lib/owlcarousel/owl.carousel.min.js"
          strategy="afterInteractive"
        />
        <Script
          src="/lib/counterup/counterup.min.js"
          strategy="afterInteractive"
        />
        <Script src="/js/main.js" strategy="afterInteractive" />
      </body>
    </html>
  );
}
